os:
  - linux

language: php

php:
  - '7.3'

before_script:
  - composer self-update
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

script:
  - vendor/bin/phpunit --coverage-text --testdox
